-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.inference_inferenced_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.inference_inferenced_id_seq
    OWNED BY public.inference.inferenced_id;

ALTER SEQUENCE public.inference_inferenced_id_seq
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.inference
(
    image_inference_id integer NOT NULL DEFAULT nextval('inference_inferenced_id_seq'::regclass),
    media_path text COLLATE pg_catalog."default" NOT NULL,
    media_type text COLLATE pg_catalog."default" NOT NULL,
    inferenced_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_inference jsonb NOT NULL DEFAULT '{}'::jsonb,
    video_inference jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT inference_pkey PRIMARY KEY (inferenced_id)
);

CREATE SEQUENCE IF NOT EXISTS public.image_inference_analytics_image_inference_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.image_inference_analytics_image_inference_id_seq
    OWNED BY public.image_inference_analytics.image_inference_id;

ALTER SEQUENCE public.image_inference_analytics_image_inference_id_seq
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.image_inference_analytics
(
    image_inference_id integer NOT NULL DEFAULT nextval('image_inference_analytics_image_inference_id_seq'::regclass),
    inference_id integer NOT NULL,
    class_name text[] COLLATE pg_catalog."default" NOT NULL,
    class_id integer[] NOT NULL,
    confidence numeric[] NOT NULL,
    x1 numeric[] NOT NULL,
    y1 numeric[] NOT NULL,
    x2 numeric[] NOT NULL,
    y2 numeric[] NOT NULL,
    CONSTRAINT image_inference_key PRIMARY KEY (image_inference_id)
        INCLUDE(image_inference_id),
    CONSTRAINT fk_image_inference FOREIGN KEY (inference_id)
        REFERENCES public.inference (inferenced_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
        NOT VALID
);

COMMENT ON TABLE public.image_inference_analytics
    IS 'Acquires the each image''s inference results analytics';

CREATE SEQUENCE IF NOT EXISTS public.video_inference_analytics_video_inference_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.video_inference_analytics_video_inference_id_seq
    OWNED BY public.video_inference_analytics.video_inference_id;

ALTER SEQUENCE public.video_inference_analytics_video_inference_id_seq
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.video_inference_analytics
(
    video_inference_id serial NOT NULL DEFAULT nextval('video_inference_analytics_video_inference_id_seq'::regclass),
    inference_id integer NOT NULL,
    class_name text[] COLLATE pg_catalog."default" NOT NULL,
    class_id integer[] NOT NULL,
    confidence numeric[] NOT NULL,
    x1 numeric[] NOT NULL,
    y1 numeric[] NOT NULL,
    x2 numeric[] NOT NULL,
    y2 numeric[] NOT NULL,
    CONSTRAINT pk_video_inference PRIMARY KEY (video_inference_id),
    CONSTRAINT video_inference_fk FOREIGN KEY (inference_id)
        REFERENCES public.inference (inferenced_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
        NOT VALID
);

COMMENT ON TABLE public.video_inference_analytics
    IS 'Analytics of the fine-tuned YOLOv11 video inferencing';

COMMENT ON CONSTRAINT video_inference_fk ON public.video_inference_analytics
    IS 'references the inference id in the inference table';

END;